Repository MLH-Fellowship/prep-project-jan-2022, pull requests merged in 2022-01, with the labels that each got.

#22 Issue#5 map for location
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/components/WeatherMap/WeatherMap.css
  src/components/WeatherMap/WeatherMap.js
  yarn.lock
Labels: approvals-neeeded, RTC

#32 Fix ESLint and Prettier rule violations
  .eslintrc.json
  src/App.js
  src/components/WeatherMap/WeatherMap.js
Labels: RTC

#19 feat: show weather info current location instead of "New York City"
  src/App.js
Labels: RTC

#37 Bump caniuse-lite [#36]
  yarn.lock
Labels: RTC

#40 Add MUI as a project dependency
  package.json
  yarn.lock
Labels: RTC

#26 feat: Add PWA integration
  public/manifest.json
  src/index.js
  src/service-worker.js
  src/serviceWorkerRegistration.js
Labels: RTC

#38 Implement a Central OpenWeatherMap API Wrapper with Caching
  src/lib/OpenWeatherMap/OpenWeatherMap.mjs
Labels: RTC

#59 Integrate OpenWeatherMap API wrapper and Refactor Components
  .eslintrc.json
  package.json
  src/App.js
  src/App.test.js
  src/assets/images/haze.jpg
  src/assets/images/squall.png
  src/assets/images/tornado.jpg
  src/components/CriticalAlerts/Alert.css
  src/components/CriticalAlerts/Alert.js
  src/components/CurrentStatus.css
  src/components/CurrentStatus.js
  src/components/Loader/Loader.jsx
  src/components/PlaceholderSkeleton/Placeholder.jsx
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/assets/cities.json
  src/components/WeatherMap/WeatherMap.css
  src/components/WeatherMap/WeatherMap.js
  src/components/carousel/ForecastCarousel.js
  src/components/carousel/WeatherCard.js
  src/components/playground/Demo.css
  src/components/playground/Demo.jsx
  src/components/playground/Elements.jsx
  src/index.js
  src/lib/OpenWeatherMap/OpenWeatherMap.mjs
Labels: help wanted
